// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AppInstallStackVersionRun app install stack version run
//
// swagger:model app.InstallStackVersionRun
type AppInstallStackVersionRun struct {

	// composite status
	CompositeStatus *AppCompositeStatus `json:"composite_status,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// created by id
	CreatedByID string `json:"created_by_id,omitempty"`

	// data
	Data map[string]string `json:"data,omitempty"`

	// data contents
	DataContents map[string]any `json:"data_contents,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// Kind is the operation this run represents. provision = first-time create,
	// reprovision = idempotent reconcile of an existing install, deprovision =
	// tear-down. default:'provision' lets gorm auto-migrate back-fill historical
	// rows; BeforeCreate validates the value.
	Kind struct {
		AppInstallStackVersionRunKind
	} `json:"kind,omitempty"`

	// LogStream is populated transiently:
	//   - On the POST response: with WriteToken + RunnerAPIURL so the SDK can
	//     start pushing logs immediately.
	//   - On GET-runs (via Preload): without WriteToken, so the dashboard can
	//     find the stream to render but can't write to it.
	LogStream struct {
		AppLogStream
	} `json:"log_stream,omitempty"`

	// LogStreamID is the OTLP log stream the SDK pushes provisioning logs to.
	// Persisted so the PATCH handler can close the stream on terminal status.
	LogStreamID string `json:"log_stream_id,omitempty"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`
}

// Validate validates this app install stack version run
func (m *AppInstallStackVersionRun) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCompositeStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateKind(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLogStream(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppInstallStackVersionRun) validateCompositeStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.CompositeStatus) { // not required
		return nil
	}

	if m.CompositeStatus != nil {
		if err := m.CompositeStatus.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("composite_status")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("composite_status")
			}

			return err
		}
	}

	return nil
}

func (m *AppInstallStackVersionRun) validateKind(formats strfmt.Registry) error {
	if swag.IsZero(m.Kind) { // not required
		return nil
	}

	return nil
}

func (m *AppInstallStackVersionRun) validateLogStream(formats strfmt.Registry) error {
	if swag.IsZero(m.LogStream) { // not required
		return nil
	}

	return nil
}

// ContextValidate validate this app install stack version run based on the context it is used
func (m *AppInstallStackVersionRun) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCompositeStatus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateKind(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLogStream(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppInstallStackVersionRun) contextValidateCompositeStatus(ctx context.Context, formats strfmt.Registry) error {

	if m.CompositeStatus != nil {

		if swag.IsZero(m.CompositeStatus) { // not required
			return nil
		}

		if err := m.CompositeStatus.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("composite_status")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("composite_status")
			}

			return err
		}
	}

	return nil
}

func (m *AppInstallStackVersionRun) contextValidateKind(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

func (m *AppInstallStackVersionRun) contextValidateLogStream(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *AppInstallStackVersionRun) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppInstallStackVersionRun) UnmarshalBinary(b []byte) error {
	var res AppInstallStackVersionRun
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
