// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// AppInstallStackVersionRunKind app install stack version run kind
//
// swagger:model app.InstallStackVersionRunKind
type AppInstallStackVersionRunKind string

func NewAppInstallStackVersionRunKind(value AppInstallStackVersionRunKind) *AppInstallStackVersionRunKind {
	return &value
}

// Pointer returns a pointer to a freshly-allocated AppInstallStackVersionRunKind.
func (m AppInstallStackVersionRunKind) Pointer() *AppInstallStackVersionRunKind {
	return &m
}

const (

	// AppInstallStackVersionRunKindProvision captures enum value "provision"
	AppInstallStackVersionRunKindProvision AppInstallStackVersionRunKind = "provision"

	// AppInstallStackVersionRunKindReprovision captures enum value "reprovision"
	AppInstallStackVersionRunKindReprovision AppInstallStackVersionRunKind = "reprovision"

	// AppInstallStackVersionRunKindDeprovision captures enum value "deprovision"
	AppInstallStackVersionRunKindDeprovision AppInstallStackVersionRunKind = "deprovision"
)

// for schema
var appInstallStackVersionRunKindEnum []any

func init() {
	var res []AppInstallStackVersionRunKind
	if err := json.Unmarshal([]byte(`["provision","reprovision","deprovision"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		appInstallStackVersionRunKindEnum = append(appInstallStackVersionRunKindEnum, v)
	}
}

func (m AppInstallStackVersionRunKind) validateAppInstallStackVersionRunKindEnum(path, location string, value AppInstallStackVersionRunKind) error {
	if err := validate.EnumCase(path, location, value, appInstallStackVersionRunKindEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this app install stack version run kind
func (m AppInstallStackVersionRunKind) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateAppInstallStackVersionRunKindEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this app install stack version run kind based on context it is used
func (m AppInstallStackVersionRunKind) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
