// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServiceUpdateInstallStackVersionRunRequest service update install stack version run request
//
// swagger:model service.UpdateInstallStackVersionRunRequest
type ServiceUpdateInstallStackVersionRunRequest struct {

	// data
	Data map[string]any `json:"data,omitempty"`

	// Status must be "succeeded" or "failed"; runs are created as "running".
	// Required: true
	Status struct {
		AppStatus
	} `json:"status"`

	// status description
	StatusDescription string `json:"status_description,omitempty"`
}

// Validate validates this service update install stack version run request
func (m *ServiceUpdateInstallStackVersionRunRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServiceUpdateInstallStackVersionRunRequest) validateStatus(formats strfmt.Registry) error {

	return nil
}

// ContextValidate validate this service update install stack version run request based on the context it is used
func (m *ServiceUpdateInstallStackVersionRunRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateStatus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServiceUpdateInstallStackVersionRunRequest) contextValidateStatus(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *ServiceUpdateInstallStackVersionRunRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceUpdateInstallStackVersionRunRequest) UnmarshalBinary(b []byte) error {
	var res ServiceUpdateInstallStackVersionRunRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
