// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateInstallStackVersionRunParams creates a new CreateInstallStackVersionRunParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateInstallStackVersionRunParams() *CreateInstallStackVersionRunParams {
	return &CreateInstallStackVersionRunParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateInstallStackVersionRunParamsWithTimeout creates a new CreateInstallStackVersionRunParams object
// with the ability to set a timeout on a request.
func NewCreateInstallStackVersionRunParamsWithTimeout(timeout time.Duration) *CreateInstallStackVersionRunParams {
	return &CreateInstallStackVersionRunParams{
		timeout: timeout,
	}
}

// NewCreateInstallStackVersionRunParamsWithContext creates a new CreateInstallStackVersionRunParams object
// with the ability to set a context for a request.
func NewCreateInstallStackVersionRunParamsWithContext(ctx context.Context) *CreateInstallStackVersionRunParams {
	return &CreateInstallStackVersionRunParams{
		Context: ctx,
	}
}

// NewCreateInstallStackVersionRunParamsWithHTTPClient creates a new CreateInstallStackVersionRunParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateInstallStackVersionRunParamsWithHTTPClient(client *http.Client) *CreateInstallStackVersionRunParams {
	return &CreateInstallStackVersionRunParams{
		HTTPClient: client,
	}
}

/*
CreateInstallStackVersionRunParams contains all the parameters to send to the API endpoint

	for the create install stack version run operation.

	Typically these are written to a http.Request.
*/
type CreateInstallStackVersionRunParams struct {

	/* Kind.

	   run kind (provision/reprovision/deprovision)
	*/
	Kind string

	/* PhoneHomeID.

	   stack version phone-home ID (used as the URL secret)
	*/
	PhoneHomeID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create install stack version run params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateInstallStackVersionRunParams) WithDefaults() *CreateInstallStackVersionRunParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create install stack version run params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateInstallStackVersionRunParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create install stack version run params
func (o *CreateInstallStackVersionRunParams) WithTimeout(timeout time.Duration) *CreateInstallStackVersionRunParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create install stack version run params
func (o *CreateInstallStackVersionRunParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create install stack version run params
func (o *CreateInstallStackVersionRunParams) WithContext(ctx context.Context) *CreateInstallStackVersionRunParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create install stack version run params
func (o *CreateInstallStackVersionRunParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create install stack version run params
func (o *CreateInstallStackVersionRunParams) WithHTTPClient(client *http.Client) *CreateInstallStackVersionRunParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create install stack version run params
func (o *CreateInstallStackVersionRunParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKind adds the kind to the create install stack version run params
func (o *CreateInstallStackVersionRunParams) WithKind(kind string) *CreateInstallStackVersionRunParams {
	o.SetKind(kind)
	return o
}

// SetKind adds the kind to the create install stack version run params
func (o *CreateInstallStackVersionRunParams) SetKind(kind string) {
	o.Kind = kind
}

// WithPhoneHomeID adds the phoneHomeID to the create install stack version run params
func (o *CreateInstallStackVersionRunParams) WithPhoneHomeID(phoneHomeID string) *CreateInstallStackVersionRunParams {
	o.SetPhoneHomeID(phoneHomeID)
	return o
}

// SetPhoneHomeID adds the phoneHomeId to the create install stack version run params
func (o *CreateInstallStackVersionRunParams) SetPhoneHomeID(phoneHomeID string) {
	o.PhoneHomeID = phoneHomeID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateInstallStackVersionRunParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param kind
	if err := r.SetPathParam("kind", o.Kind); err != nil {
		return err
	}

	// path param phone_home_id
	if err := r.SetPathParam("phone_home_id", o.PhoneHomeID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
