// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/nuon-runner-go/models"
)

// CreateInstallStackVersionRunReader is a Reader for the CreateInstallStackVersionRun structure.
type CreateInstallStackVersionRunReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateInstallStackVersionRunReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 201:
		result := NewCreateInstallStackVersionRunCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewCreateInstallStackVersionRunNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateInstallStackVersionRunInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /v1/stack-runs/{phone_home_id}/kind/{kind}] CreateInstallStackVersionRun", response, response.Code())
	}
}

// NewCreateInstallStackVersionRunCreated creates a CreateInstallStackVersionRunCreated with default headers values
func NewCreateInstallStackVersionRunCreated() *CreateInstallStackVersionRunCreated {
	return &CreateInstallStackVersionRunCreated{}
}

/*
CreateInstallStackVersionRunCreated describes a response with status code 201, with default header values.

Created
*/
type CreateInstallStackVersionRunCreated struct {
	Payload *models.AppInstallStackVersionRun
}

// IsSuccess returns true when this create install stack version run created response has a 2xx status code
func (o *CreateInstallStackVersionRunCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create install stack version run created response has a 3xx status code
func (o *CreateInstallStackVersionRunCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create install stack version run created response has a 4xx status code
func (o *CreateInstallStackVersionRunCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create install stack version run created response has a 5xx status code
func (o *CreateInstallStackVersionRunCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create install stack version run created response a status code equal to that given
func (o *CreateInstallStackVersionRunCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the create install stack version run created response
func (o *CreateInstallStackVersionRunCreated) Code() int {
	return 201
}

func (o *CreateInstallStackVersionRunCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/stack-runs/{phone_home_id}/kind/{kind}][%d] createInstallStackVersionRunCreated %s", 201, payload)
}

func (o *CreateInstallStackVersionRunCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/stack-runs/{phone_home_id}/kind/{kind}][%d] createInstallStackVersionRunCreated %s", 201, payload)
}

func (o *CreateInstallStackVersionRunCreated) GetPayload() *models.AppInstallStackVersionRun {
	return o.Payload
}

func (o *CreateInstallStackVersionRunCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AppInstallStackVersionRun)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateInstallStackVersionRunNotFound creates a CreateInstallStackVersionRunNotFound with default headers values
func NewCreateInstallStackVersionRunNotFound() *CreateInstallStackVersionRunNotFound {
	return &CreateInstallStackVersionRunNotFound{}
}

/*
CreateInstallStackVersionRunNotFound describes a response with status code 404, with default header values.

Not Found
*/
type CreateInstallStackVersionRunNotFound struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this create install stack version run not found response has a 2xx status code
func (o *CreateInstallStackVersionRunNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create install stack version run not found response has a 3xx status code
func (o *CreateInstallStackVersionRunNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create install stack version run not found response has a 4xx status code
func (o *CreateInstallStackVersionRunNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this create install stack version run not found response has a 5xx status code
func (o *CreateInstallStackVersionRunNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this create install stack version run not found response a status code equal to that given
func (o *CreateInstallStackVersionRunNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the create install stack version run not found response
func (o *CreateInstallStackVersionRunNotFound) Code() int {
	return 404
}

func (o *CreateInstallStackVersionRunNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/stack-runs/{phone_home_id}/kind/{kind}][%d] createInstallStackVersionRunNotFound %s", 404, payload)
}

func (o *CreateInstallStackVersionRunNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/stack-runs/{phone_home_id}/kind/{kind}][%d] createInstallStackVersionRunNotFound %s", 404, payload)
}

func (o *CreateInstallStackVersionRunNotFound) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *CreateInstallStackVersionRunNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateInstallStackVersionRunInternalServerError creates a CreateInstallStackVersionRunInternalServerError with default headers values
func NewCreateInstallStackVersionRunInternalServerError() *CreateInstallStackVersionRunInternalServerError {
	return &CreateInstallStackVersionRunInternalServerError{}
}

/*
CreateInstallStackVersionRunInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type CreateInstallStackVersionRunInternalServerError struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this create install stack version run internal server error response has a 2xx status code
func (o *CreateInstallStackVersionRunInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create install stack version run internal server error response has a 3xx status code
func (o *CreateInstallStackVersionRunInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create install stack version run internal server error response has a 4xx status code
func (o *CreateInstallStackVersionRunInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create install stack version run internal server error response has a 5xx status code
func (o *CreateInstallStackVersionRunInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create install stack version run internal server error response a status code equal to that given
func (o *CreateInstallStackVersionRunInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create install stack version run internal server error response
func (o *CreateInstallStackVersionRunInternalServerError) Code() int {
	return 500
}

func (o *CreateInstallStackVersionRunInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/stack-runs/{phone_home_id}/kind/{kind}][%d] createInstallStackVersionRunInternalServerError %s", 500, payload)
}

func (o *CreateInstallStackVersionRunInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/stack-runs/{phone_home_id}/kind/{kind}][%d] createInstallStackVersionRunInternalServerError %s", 500, payload)
}

func (o *CreateInstallStackVersionRunInternalServerError) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *CreateInstallStackVersionRunInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
