// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/nuon-runner-go/models"
)

// UpdateInstallStackVersionRunReader is a Reader for the UpdateInstallStackVersionRun structure.
type UpdateInstallStackVersionRunReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateInstallStackVersionRunReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateInstallStackVersionRunOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateInstallStackVersionRunBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateInstallStackVersionRunNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUpdateInstallStackVersionRunInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PATCH /v1/stack-runs/{phone_home_id}/{run_id}] UpdateInstallStackVersionRun", response, response.Code())
	}
}

// NewUpdateInstallStackVersionRunOK creates a UpdateInstallStackVersionRunOK with default headers values
func NewUpdateInstallStackVersionRunOK() *UpdateInstallStackVersionRunOK {
	return &UpdateInstallStackVersionRunOK{}
}

/*
UpdateInstallStackVersionRunOK describes a response with status code 200, with default header values.

OK
*/
type UpdateInstallStackVersionRunOK struct {
	Payload *models.AppInstallStackVersionRun
}

// IsSuccess returns true when this update install stack version run o k response has a 2xx status code
func (o *UpdateInstallStackVersionRunOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update install stack version run o k response has a 3xx status code
func (o *UpdateInstallStackVersionRunOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update install stack version run o k response has a 4xx status code
func (o *UpdateInstallStackVersionRunOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update install stack version run o k response has a 5xx status code
func (o *UpdateInstallStackVersionRunOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update install stack version run o k response a status code equal to that given
func (o *UpdateInstallStackVersionRunOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update install stack version run o k response
func (o *UpdateInstallStackVersionRunOK) Code() int {
	return 200
}

func (o *UpdateInstallStackVersionRunOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /v1/stack-runs/{phone_home_id}/{run_id}][%d] updateInstallStackVersionRunOK %s", 200, payload)
}

func (o *UpdateInstallStackVersionRunOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /v1/stack-runs/{phone_home_id}/{run_id}][%d] updateInstallStackVersionRunOK %s", 200, payload)
}

func (o *UpdateInstallStackVersionRunOK) GetPayload() *models.AppInstallStackVersionRun {
	return o.Payload
}

func (o *UpdateInstallStackVersionRunOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AppInstallStackVersionRun)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUpdateInstallStackVersionRunBadRequest creates a UpdateInstallStackVersionRunBadRequest with default headers values
func NewUpdateInstallStackVersionRunBadRequest() *UpdateInstallStackVersionRunBadRequest {
	return &UpdateInstallStackVersionRunBadRequest{}
}

/*
UpdateInstallStackVersionRunBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type UpdateInstallStackVersionRunBadRequest struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this update install stack version run bad request response has a 2xx status code
func (o *UpdateInstallStackVersionRunBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update install stack version run bad request response has a 3xx status code
func (o *UpdateInstallStackVersionRunBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update install stack version run bad request response has a 4xx status code
func (o *UpdateInstallStackVersionRunBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this update install stack version run bad request response has a 5xx status code
func (o *UpdateInstallStackVersionRunBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this update install stack version run bad request response a status code equal to that given
func (o *UpdateInstallStackVersionRunBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the update install stack version run bad request response
func (o *UpdateInstallStackVersionRunBadRequest) Code() int {
	return 400
}

func (o *UpdateInstallStackVersionRunBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /v1/stack-runs/{phone_home_id}/{run_id}][%d] updateInstallStackVersionRunBadRequest %s", 400, payload)
}

func (o *UpdateInstallStackVersionRunBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /v1/stack-runs/{phone_home_id}/{run_id}][%d] updateInstallStackVersionRunBadRequest %s", 400, payload)
}

func (o *UpdateInstallStackVersionRunBadRequest) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *UpdateInstallStackVersionRunBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUpdateInstallStackVersionRunNotFound creates a UpdateInstallStackVersionRunNotFound with default headers values
func NewUpdateInstallStackVersionRunNotFound() *UpdateInstallStackVersionRunNotFound {
	return &UpdateInstallStackVersionRunNotFound{}
}

/*
UpdateInstallStackVersionRunNotFound describes a response with status code 404, with default header values.

Not Found
*/
type UpdateInstallStackVersionRunNotFound struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this update install stack version run not found response has a 2xx status code
func (o *UpdateInstallStackVersionRunNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update install stack version run not found response has a 3xx status code
func (o *UpdateInstallStackVersionRunNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update install stack version run not found response has a 4xx status code
func (o *UpdateInstallStackVersionRunNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this update install stack version run not found response has a 5xx status code
func (o *UpdateInstallStackVersionRunNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this update install stack version run not found response a status code equal to that given
func (o *UpdateInstallStackVersionRunNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the update install stack version run not found response
func (o *UpdateInstallStackVersionRunNotFound) Code() int {
	return 404
}

func (o *UpdateInstallStackVersionRunNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /v1/stack-runs/{phone_home_id}/{run_id}][%d] updateInstallStackVersionRunNotFound %s", 404, payload)
}

func (o *UpdateInstallStackVersionRunNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /v1/stack-runs/{phone_home_id}/{run_id}][%d] updateInstallStackVersionRunNotFound %s", 404, payload)
}

func (o *UpdateInstallStackVersionRunNotFound) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *UpdateInstallStackVersionRunNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUpdateInstallStackVersionRunInternalServerError creates a UpdateInstallStackVersionRunInternalServerError with default headers values
func NewUpdateInstallStackVersionRunInternalServerError() *UpdateInstallStackVersionRunInternalServerError {
	return &UpdateInstallStackVersionRunInternalServerError{}
}

/*
UpdateInstallStackVersionRunInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type UpdateInstallStackVersionRunInternalServerError struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this update install stack version run internal server error response has a 2xx status code
func (o *UpdateInstallStackVersionRunInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update install stack version run internal server error response has a 3xx status code
func (o *UpdateInstallStackVersionRunInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update install stack version run internal server error response has a 4xx status code
func (o *UpdateInstallStackVersionRunInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this update install stack version run internal server error response has a 5xx status code
func (o *UpdateInstallStackVersionRunInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this update install stack version run internal server error response a status code equal to that given
func (o *UpdateInstallStackVersionRunInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the update install stack version run internal server error response
func (o *UpdateInstallStackVersionRunInternalServerError) Code() int {
	return 500
}

func (o *UpdateInstallStackVersionRunInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /v1/stack-runs/{phone_home_id}/{run_id}][%d] updateInstallStackVersionRunInternalServerError %s", 500, payload)
}

func (o *UpdateInstallStackVersionRunInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /v1/stack-runs/{phone_home_id}/{run_id}][%d] updateInstallStackVersionRunInternalServerError %s", 500, payload)
}

func (o *UpdateInstallStackVersionRunInternalServerError) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *UpdateInstallStackVersionRunInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
