// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/nuon-runner-go/models"
)

// NewUpdateInstallStackVersionRunParams creates a new UpdateInstallStackVersionRunParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateInstallStackVersionRunParams() *UpdateInstallStackVersionRunParams {
	return &UpdateInstallStackVersionRunParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateInstallStackVersionRunParamsWithTimeout creates a new UpdateInstallStackVersionRunParams object
// with the ability to set a timeout on a request.
func NewUpdateInstallStackVersionRunParamsWithTimeout(timeout time.Duration) *UpdateInstallStackVersionRunParams {
	return &UpdateInstallStackVersionRunParams{
		timeout: timeout,
	}
}

// NewUpdateInstallStackVersionRunParamsWithContext creates a new UpdateInstallStackVersionRunParams object
// with the ability to set a context for a request.
func NewUpdateInstallStackVersionRunParamsWithContext(ctx context.Context) *UpdateInstallStackVersionRunParams {
	return &UpdateInstallStackVersionRunParams{
		Context: ctx,
	}
}

// NewUpdateInstallStackVersionRunParamsWithHTTPClient creates a new UpdateInstallStackVersionRunParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateInstallStackVersionRunParamsWithHTTPClient(client *http.Client) *UpdateInstallStackVersionRunParams {
	return &UpdateInstallStackVersionRunParams{
		HTTPClient: client,
	}
}

/*
UpdateInstallStackVersionRunParams contains all the parameters to send to the API endpoint

	for the update install stack version run operation.

	Typically these are written to a http.Request.
*/
type UpdateInstallStackVersionRunParams struct {

	/* PhoneHomeID.

	   stack version phone-home ID (used as the URL secret)
	*/
	PhoneHomeID string

	/* Req.

	   Input
	*/
	Req *models.ServiceUpdateInstallStackVersionRunRequest

	/* RunID.

	   run ID
	*/
	RunID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update install stack version run params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateInstallStackVersionRunParams) WithDefaults() *UpdateInstallStackVersionRunParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update install stack version run params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateInstallStackVersionRunParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update install stack version run params
func (o *UpdateInstallStackVersionRunParams) WithTimeout(timeout time.Duration) *UpdateInstallStackVersionRunParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update install stack version run params
func (o *UpdateInstallStackVersionRunParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update install stack version run params
func (o *UpdateInstallStackVersionRunParams) WithContext(ctx context.Context) *UpdateInstallStackVersionRunParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update install stack version run params
func (o *UpdateInstallStackVersionRunParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update install stack version run params
func (o *UpdateInstallStackVersionRunParams) WithHTTPClient(client *http.Client) *UpdateInstallStackVersionRunParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update install stack version run params
func (o *UpdateInstallStackVersionRunParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPhoneHomeID adds the phoneHomeID to the update install stack version run params
func (o *UpdateInstallStackVersionRunParams) WithPhoneHomeID(phoneHomeID string) *UpdateInstallStackVersionRunParams {
	o.SetPhoneHomeID(phoneHomeID)
	return o
}

// SetPhoneHomeID adds the phoneHomeId to the update install stack version run params
func (o *UpdateInstallStackVersionRunParams) SetPhoneHomeID(phoneHomeID string) {
	o.PhoneHomeID = phoneHomeID
}

// WithReq adds the req to the update install stack version run params
func (o *UpdateInstallStackVersionRunParams) WithReq(req *models.ServiceUpdateInstallStackVersionRunRequest) *UpdateInstallStackVersionRunParams {
	o.SetReq(req)
	return o
}

// SetReq adds the req to the update install stack version run params
func (o *UpdateInstallStackVersionRunParams) SetReq(req *models.ServiceUpdateInstallStackVersionRunRequest) {
	o.Req = req
}

// WithRunID adds the runID to the update install stack version run params
func (o *UpdateInstallStackVersionRunParams) WithRunID(runID string) *UpdateInstallStackVersionRunParams {
	o.SetRunID(runID)
	return o
}

// SetRunID adds the runId to the update install stack version run params
func (o *UpdateInstallStackVersionRunParams) SetRunID(runID string) {
	o.RunID = runID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateInstallStackVersionRunParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param phone_home_id
	if err := r.SetPathParam("phone_home_id", o.PhoneHomeID); err != nil {
		return err
	}
	if o.Req != nil {
		if err := r.SetBodyParam(o.Req); err != nil {
			return err
		}
	}

	// path param run_id
	if err := r.SetPathParam("run_id", o.RunID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
